services:
  pastebin:
    build: .
    ports:
      - "3636:3636"
    environment:
      - PASTEBIN_TIMEZONE=America/Los_Angeles
    volumes:
      - pastebin-data:/data
    restart: unless-stopped
    image: local-pastebin

volumes:
  pastebin-data:
